### ISSUE TITLE
the eval's result

### ISSUE THREAD

**Issue by cuixianheng** [alinlab/CSI#10]
I used the pre-trained model cifar_last.model you provided, and then ran the following code:
**python eval.py --mode ood_pre --dataset  cifar10 --model resnet18  --ood_score CSI --shift_trans_type rotation --print_score --ood_samples 10  --resize_factor 0.54 --resize_fix --one_class_idx 0 --load_path  "./checkpoint/cifar_last.model"**
 and the final result was very terrible:
[one_class_mean CSI 0.4087] [one_class_mean best 0.4087]
What causes this result？

**Comment by Jihoon-Tack** [comment]
Thank you for your interest in our paper!

I believe the checkpoint is trained under **multi-class CIFAR-10** (using all CIFAR-10 datasets as in-distribution), and your evaluation code is for **one-class OOD detection** (assuming one class of CIFAR-10 is in-distribution while the other 9 classes are OOD).

To properly evaluate CSI with the given checkpoint, run the following code (remove --one_class_idx option):\
`python eval.py --mode ood_pre --dataset cifar10 --model resnet18 --ood_score CSI --shift_trans_type rotation --print_score --ood_samples 10 --resize_factor 0.54 --resize_fix --load_path "./checkpoint/cifar_last.model"`

We will release all one-class OOD detection checkpoints in the near future (asap)!

Thank you again for your interest!

**Comment by Jihoon-Tack** [comment]
**[update] We have uploaded all checkpoints for CIFAR-10 one class OOD detection**

**Comment by cuixianheng** [comment]
I test the code, and finally the one_class_idx_0's **AUC is 0.9011**,  **thanks for your great work**!!!

I have the another question aboout the **image_size**, in the datasets.py, if the dataset == 'cifar10', the image_size is (32,32,3), is it **(H,W,C)**? in the transform_layers.py, the class RandomResizedCropLayer's parameter size is **(C, W, H)**, Why are they not equal, am I wrong?

**Comment by Jihoon-Tack** [comment]
Thank you! Glad to hear that the results came out well!

The size input for the `F.adaptive_avg_pool2d` function should be (C, W, H): this operation is for the resizing operation e.g., if reducing 256, 256 image size into 224, 224.\

Here is the example code for `F.adaptive_avg_pool2d` function:
```
>>> a = torch.rand(128, 3, 64, 64)
>>> out = F.adaptive_avg_pool2d(a, (32, 32, 3))
>>> out.shape
torch.Size([128, 3, 32, 32])
```

Thank you again for your interest and feel free to ask any questions!
