### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by cuixianheng** [alinlab/CSI#11]
I run the flowing code：
**CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 train.py --dataset cifar10 --model resnet18 --mode simclr_CSI --shift_trans_type rotation --batch_size 32 --one_class_idx 0**
and I meet the error:

RuntimeError: Broken pipe
    work = _default_pg.broadcast([tensor], opts)
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: Broken pipe
RuntimeError: Broken pipe

I don't know why .

**Comment by Jihoon-Tack** [comment]
Hi, it is possible to share the version of your packages?

Maybe the error can be related to the distributed launch.
Does the same error occur when running with a single GPU?
`CUDA_VISIBLE_DEVICES=0 python train.py --dataset cifar10 --model resnet18 --mode simclr_CSI --shift_trans_type rotation --batch_size 32 --one_class_idx 0`

Thank you,
Jihoon

**Comment by cuixianheng** [comment]
the follwing is the version of my packages:
absl-py                0.9.0
anykeystore            0.2
apex                   0.1
asn1crypto             0.24.0
astor                  0.8.1
attrs                  20.2.0
cachetools             4.1.1
certifi                2018.1.18
chardet                3.0.4
cryptacular            1.5.5
cryptography           2.1.4
cycler                 0.10.0
defusedxml             0.6.0
diffdist               0.1
future                 0.18.2
gast                   0.2.2
google-auth            1.21.1
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.27.2
h5py                   2.10.0
hupper                 1.10.2
idna                   2.6
joblib                 0.14.1
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.0
keyring                10.6.0
keyrings.alt           3.0
kiwisolver             1.1.0
kornia                 0.4.0
Markdown               3.2.1
matplotlib             3.2.0
numpy                  1.18.2
oauthlib               3.1.0
onnx                   1.6.0
opencv-python          4.2.0.32
opt-einsum             3.2.0
packaging              20.4
PasteDeploy            2.1.0
pbkdf2                 1.3
Pillow                 7.0.0
pip                    20.2.3
plaster                1.0
plaster-pastedeploy    0.7
protobuf               3.11.3
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycrypto               2.6.1
pygobject              3.26.1
pyparsing              2.4.6
pyramid                1.10.4
pyramid-mailer         0.15.1
python-dateutil        2.8.1
python3-openid         3.1.0
pytorch-lightning      0.9.0
pyxdg                  0.25
PyYAML                 5.3.1
repoze.sendmail        4.4.1
requests               2.24.0
requests-oauthlib      1.3.0
rsa                    4.6
scikit-learn           0.22.2.post1
scipy                  1.4.1
SecretStorage          2.3.1
setuptools             46.0.0
six                    1.11.0
SQLAlchemy             1.3.15
ssh-import-id          5.7
tensorboard            2.2.0
tensorboard-plugin-wit 1.7.0
tensorboardX           2.1
tensorflow             1.15.0
tensorflow-estimator   1.15.1
termcolor              1.1.0
terminaltables         3.1.0
torch                  1.6.0
torchlars              0.1.2
torchvision            0.7.0
tqdm                   4.43.0
transaction            3.0.0
translationstring      1.3
typing-extensions      3.7.4.1
urllib3                1.22
velruse                1.1.1
venusian               3.0.0
WebOb                  1.8.6
Werkzeug               1.0.0
wheel                  0.30.0
wrapt                  1.12.1
WTForms                2.2.1
wtforms-recaptcha      0.3.2
zope.deprecation       4.4.0
zope.interface         4.7.2
zope.sqlalchemy        1.3

**There is no error when I use two GPUs**，it just reports an error when I use four GPUs.
Thank you very much.

**Comment by Jihoon-Tack** [comment]
Hi!

We have validated our code with torch 1.4.0, torchvision 0.5.0 and couldn't found any error.
Maybe the torch version can be the issue for your error.

Right now, we don't have a plan to update the code for the later torch version, but we will notify you immediately if an update is made.

Thank you again for the interest and reporting the issue.
