### ISSUE TITLE
Is it possible to train on a different dataset?

### ISSUE THREAD

**Issue by jodumagpi** [alinlab/CSI#12]
Thank you for your great work. I'm just wondering if it's possible to train on my own dataset?

**Comment by Jihoon-Tack** [comment]
Hi, thank you for your interest!

You can use personal datasets to train CSI.
You can simply add your personal datasets in `get_dataset` function in `datasets/datasets.py`.
And also add OOD datasets that you want to evaluate.

If you have any questions or problems, feel free to reopen the issue.

Thank you!
