### ISSUE TITLE
cannot download imagenet-30

### ISSUE THREAD

**Issue by XavierXiao** [alinlab/CSI#13]
I cannot download the ImageNet-30 dataset. It says 

> Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

**Comment by Jihoon-Tack** [comment]
Hi, thank you for the interest

We are using the link for ImageNet-30 from https://github.com/hendrycks/ss-ood, therefore we are not sure about the cause. 

I've seen a similar error when downloading CelebA or other datasets from google drive, but in my case, it resolved over time.

Thank you
