### ISSUE TITLE
some confusion

### ISSUE THREAD

**Issue by tommying** [alinlab/CSI#14]
Hi, sir. Thanks for your excellent idea!
Now I have some confusion:
1.  The paper said the contrastive loss makes the norm of in-distribution samples relatively larger than OOD samples (P23). But according to the cosine similarity formula, when the cosine similarity of two similar features increases, the norm should become smaller.
2.  You said the code use the inner product in our implementation, which is the product of cosine similarity and norm. But the inner product is not equal to formula(6) from the paper.
3.   I don't understand how use the shift transformations in the simCLR (how to putting formula 3 into formula 2? Is there still have positive pairs in the molecular of formula 1?) and why is formula 4 needed?

I hope you can help me out.
I am looking forward to your reply!

**Comment by sangwoomo** [comment]
Hi @tommying, thank you for your interest!

1. The cosine similarity formula u * v / ||u|| * ||v|| itself does not imply anything about the norm, as the norm of u (so as v) affects both the numerator and denominator. However, we hypothesize that the SimCLR objective implicitly increases the norm, as it is hard to decrease the Euclidian distance of the features u and v; hence the model pushes both features (yet keeping the Euclidian distance) to decrease the cosine similarity.
2. Note that sim(z(x_m), z(x)) ||z(x)|| = (z(x_m) * z(x) / ||z(x_m)|| * ||z(x)||) * ||z(x)|| = z(x) * (z(x_m) / ||z(x_m)||), where z(x) is f_sim and z(x_m) / ||z(x_m)|| are P.axis in our code.
3. SimCLR (Eq. (2)) only pushes unshifted negative batches B, but CSI (Eq. (3)) also pushes shifted negative batches B_S. By substituting B to B_S in Eq. (2), you can derive that the objective is changed from L_con(x^1,x^2,B) to L_con(x^1,x^2,B_S). Also, Eq. (4) is used to further discriminate the shifting transformations. Intuitively, there are no reason to not use the additional shifting transformation labels, and it indeed improves the performance as we show in our ablation study (Table 7a).

Best regards,

**Comment by tommying** [comment]
thank you, sir.

**Comment by Minqi824** [comment]
- I also confused about problem 1. The first part of Eq. (6) is intuitive: the OOD samples' embedding is far from the ID samples' embedding, so the sim(z(x_m), z(x)) would be small if x is OOD.

However, @sangwoomo explains that the model pushes both features' norm to decrease the cosine similarity. I am confused that how the difference of ID & OOD samples is shown in the term ||z(x)||? Could you explain it more?

- Besides, "we hypothesize that the SimCLR objective implicitly increases the norm" seems not to explain the reason why the term ||z(x)|| is smaller for OOD samples.

Very thanks!
