### ISSUE TITLE
run SimCLR

### ISSUE THREAD

**Issue by smart0eddie** [alinlab/CSI#15]
Hi, 

I'm running evaluation of simclr following the command in README.md 
python eval.py --mode ood_pre --dataset <DATASET> --model <NETWORK> --ood_score simclr --shift_trans_type rotation --print_score --ood_samples 10 --resize_factor 0.54 --resize_fix --one_class_idx <One-Class-Index> --load_path <MODEL_PATH>

Python reports error at 
evals/ood_pre.py", line 120, in get_scores
    score += (f_sim[shi] * P.axis[shi]).sum(dim=1).max().item() * P.weight_sim[shi]
because P.K_shift is 4 with --shift_trans_type rotation 
and P.weight_sim is [1] with --ood_score simclr

It seems simclr should be trained and evaluated with --shift_trans_type option disabled

**Comment by sangwoomo** [comment]
Hi, we didn't apply shifting transformations for vanilla SimCLR. However, you may modify the code to test it :)
