### ISSUE TITLE
Is custom one-class learning possible?

### ISSUE THREAD

**Issue by ik8851ik** [alinlab/CSI#22]
Hello,

Thank you for sharing hard work.

I am currently trying to perform one-class learning with my own dataset.(with no ground truth)
Is the 'Unlabeled one-class' training method you guided available to train my own custom one-class dataset?
I am facing difficulties and can not figure out whether it is my mistake or it wasn't for custom one-class dataset from the first.

Thank you.

**Comment by sangwoomo** [comment]
Hi @ik8851ik,

Yes, unlabeled one-class is the right one.
Could you elaborate your situation (e.g., dataset?)
As we stated in the paper, our method needs a proper augmentations for the dataset, and it may be a problem.

Best regards,

**Comment by ik8851ik** [comment]
Oh.. I only have a folder of images(only one class without any abnormality), and trying to train it even thought this won't be able to evaluate(inference only). 
I am facing difficulty setting the requirements, and cannot try out the guild now....
I was curious whether I will be able to do the unlabeled one-class training.
Thank you for the kind reply.
