### ISSUE TITLE
about cosine similarity 

### ISSUE THREAD

**Issue by tommying** [alinlab/CSI#23]
hi, sir.

In your paper , both training model and test model are used cosine similarity. But in your code, you only used the inner product.

1.  In training model, there [https://github.com/alinlab/CSI/blob/60742b60a16501350eca823fcc910ddd10f7a379/training/contrastive_loss.py#L21](url) only use torch.mm() to calculate the inner product? 
why use the inner product to training model instead the cosine similarity?

2.  You said in other issues that the code use the inner product to calculate the score , which is the product of cosine similarity and norm. 
      Because cosine similarity  sim(z, z′) := z · z′ /  ||z|| ||z′||,  so, the product of cosine similarity and norm should be 
sim(x, x_m))·||x||·||x_m||.

      But, CSI computes the maximum cosine similarity over the training samples and the norm of the representation(e.g., max_m     sim(x, x_m) · ||x|| .)
      if we followed the this (the inner product to calculate the score , which is the product of cosine similarity and norm.), test score will be  max_m     sim(x, x_m) · ||x|| ||x_m||. that make me confuse.

I hope you can help me out.
I am looking forward to your reply!

**Comment by sangwoomo** [comment]
Hi,

1. In training, inner product = cosine similarity since we normalized the projection features.
2. Similarly, in inference, P.axis is normalized, hence inner(z, normalized(z')) = sim(z, z') * norm(z).

Now I recognize that the inference code could be somewhat confusing :(

**Comment by tommying** [comment]
@sangwoomo  very thanks!
