### ISSUE TITLE
Is the calculated score not a value of 0-1？

### ISSUE THREAD

**Issue by cuixianheng** [alinlab/CSI#25]
Is the calculated score not a value of 0-1？

**Comment by jihoontack** [comment]
Thank you for the interest in our paper.

The score is a positive value that is not normalized into 0-1.

**Comment by cuixianheng** [comment]
But shouldn't the predicted probability entered when calculating the auc index be a value of 0-1?

**Comment by sangwoomo** [comment]
To measure AUROC, we compute the scores for all samples (both in-distribution and OOD) and only check the relative scale of the scores. One may normalize the score into 0-1 from in-distribution (or in-distribution + OOD) samples.
