### ISSUE TITLE
Is the comparison loss of simclr and simclr-csi the same?

### ISSUE THREAD

**Issue by zhaijianyang** [alinlab/CSI#28]
Isn't the enhanced sample a negative sample? Why are the two contrast losses the same?

**Comment by jihoontack** [comment]
Hi, thank you for the interest in our work!

I didn't catch up on the question properly. 
Do you mean
- (a) the computed value of the `simclr` and `simclr-csi` is the same?
- (b) the loss formula is the same?

Best,
Jihoon

**Comment by zhaijianyang** [comment]
the contrastive loss formula is the same

**Comment by sangwoomo** [comment]
If my understanding is correct, the enhanced (or shifted) sample `S(x)` is negative in perspective of the original sample `x`.
We only consider `S(T1(x))` and `S(T2(x))` be positive, and they are always negative for any `T3(x)`.
