### ISSUE TITLE
test score

### ISSUE THREAD

**Issue by tommying** [alinlab/CSI#29]
I am sorry to bother you again! I have some confuse about test score:

we have 10000 test image (for cifar-10), in the code < evals/ood_pre.py >, we got 9000 ood features from 9 ood class in line 92. And we put 19000 features into     roc_auc_score()    function in line 96.

1.  Why the code compute the score use 19000 features instead 10000? Isn't there 9000 features that are duplicates here? 
      （because that 10000 test features already included 9000 features from ood class）
2. Is that   “One_class_real_mean” are the final result? (It is computed from 19000 features.)

**Comment by sangwoomo** [comment]
Hi,

1. For one-class classification, id_loader contains one class (1000 samples) and ood_loaders contain remaining ones (9000 samples). Hence, we put non-duplicated 10000 samples to compute auroc.
2. If I remember correctly, line 90 computes class-wise auroc (e.g., class 0 vs 1) and line 96 computes the average auroc (e.g., class 0 vs 1,2,...,9).

**Comment by tommying** [comment]
@sangwoomo 
Oh, god. I made some mistake.
sorry about that...
