### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by dreamflasher** [alinlab/CSI#3]
I use the following command `python3 -m torch.distributed.launch  --nproc_per_node 4  train.py --dataset cifar10 --model resnet18 --mode simclr_CSI --shift_trans_type rotation --batch_size 32 --one_class_idx 0` on a 4 GPU machine. Do I understand correctly, that this should yield comparable results to Table 1a "plane" CSI (ours) of 90%?

I have let it run a couple of times now, getting an average of 86%. What am I doing wrong?

Also, how do I interpret the result output `[one_class_mean clean_norm 0.8478] [one_class_mean similar 0.6925] [one_class_mean best 0.8478]`? Is clean_norm the norm (z) by itself? And similar the l2 to the closest training point? And best looks to me like the best of these two results, shouldn't it be the product?

**Comment by Jihoon-Tack** [comment]
Hi, 

During the training phase, the norm and cosine_similarity are used as a score function simply for tracking the training tendency (best score denotes the better value between them). Both values are not the reported value in the paper.

To use the proposed score function (s_{CSI-ens}(x)), you can execute the following code:
`python eval.py --mode ood_pre --dataset <DATASET> --model <NETWORK> --ood_score CSI --shift_trans_type rotation --print_score --ood_samples 10 --resize_factor 0.54 --resize_fix --one_class_idx <One-Class-Index> --load_path <MODEL_PATH>
`

You can find the description in `README.md` (section 3: Unlabeled one-class & multi-class).

Thank you.

**Comment by sangwoomo** [comment]
Hi Marcel,

Thank you for your interest in our paper, and sorry for your confusion.

As you mentioned, `clean_norm` and `similar` are not the final score, and we used them for our internal analysis. You can reproduce our results using the final score with `eval.py` as @Jihoon-Tack elaborated.

We will clarify the code and readme to prevent confusion of future readers.

Thanks for your clarification!

**Comment by dreamflasher** [comment]
@sangwoomo @Jihoon-Tack Thanks a lot for your fast response! With the evaluation script I get `[one_class_mean CSI 0.7301] [one_class_mean best 0.7301]`. Looks like I am still doing something wrong?

Also, do I understand correctly that I can do multi-class training, and then multi-class evaluation, so that I don't need to run the training command for each class seperately to reproduce table 1a?

**Comment by Jihoon-Tack** [comment]
Hi Marcel,

Is it possible to see your evaluation script?

The unlabeled multi-class training indicates the results from Table 2 of our paper (assuming we don't have any labels from full CIFAR-10 dataset). To obtain Table 1 (a) result, you should train individual classes of CIFAR-10 by setting `--one_class_idx`.

Thank you.

**Comment by sangwoomo** [comment]
If you run multi-class training, all classes become "in-distribution"; hence the model cannot distinguish the chosen one-class and the remaining classes (as both of them are "in"). In that case, we use different datasets as OOD.
To reproduce Table 1a, you should train a model for each class, as only the chosen on-class is in-distribution, and now the remaining classes (not trained for training) are OOD.
To sum up, you should train ten one-class models for Table 1a and one multi-class model for Table 2a.

Did you use the remaining classes (1-9) for your evaluation? It should be at least good as your training results 0.8478.
I guess `python eval.py --mode ood_pre --dataset cifar10 --model resnet18 --ood_score CSI --shift_trans_type rotation --print_score --ood_samples 10 --resize_factor 0.54 --resize_fix --one_class_idx 0 --load_path <MODEL_PATH>` would work.

**Comment by dreamflasher** [comment]
I used these commands:

Thank you so much for further explaining the evaluation procedure! 
I used the `best.model` for evaluation, while I should have used `epoch1000.model`. Now I see an auroc of `0.8975`. Amazing!

Thanks a lot for your help, and your great work!

**Comment by sangwoomo** [comment]
I think the best model should be identical to the final model (perhaps you overwrited?), but anyway, happy to hear that it works now! 😀

**Comment by Jihoon-Tack** [comment]
**[update]**

Now, instead of saving the `best.model`, we changed to save the lastest model as `last.model` by saving at every `--save_epoch`. We were saving the `best.model` based on the classification accuracy, which is not valid on the one-class anomaly detection. Your `best.model` might be saved at the beginning of the training epoch due to this issue. 

Additionally, since other people can also be confused about the `clean_norm` and `similar`, we do not evaluate OOD detection during the training phase anymore.

Thank you again for the valuable question.

**Comment by cuixianheng** [comment]
> Thank you so much for further explaining the evaluation procedure!
> I used the `best.model` for evaluation, while I should have used `epoch1000.model`. Now I see an auroc of `0.8975`. Amazing!
> 
> Thanks a lot for your help, and your great work!
