### ISSUE TITLE
Your data is 4 times bigger than Simclr. Is it fair?

### ISSUE THREAD

**Issue by junleiz** [alinlab/CSI#34]
Hello, thank you for your patient reply. I have a question. The scale of your data is 4 times bigger than that for simclr (rotation 0, 90, 180, 270). Is it fair?

**Comment by jihoontack** [comment]
Hi, thank you for your interest!

We believe applying shifting transformation is a contribution of our work.\
In SimCLR, the authors reported that rotation degrades the performance.
However, we consider it as a distribution shifting and utilize it as a self-generated out-of-distribution (OOD) for better OOD detection.

Thank you,
Jihoon
