### ISSUE TITLE
Why did you do the rotation transformation firstly and then apply the simlcr_aug？

### ISSUE THREAD

**Issue by junleiz** [alinlab/CSI#36]
Hello，Why did you do the rotation transformation firstly and then apply the simlcr_aug? Because you classify the features which transformation is applied after the simclr_aug. It is like Image—> T_transform->simclr_aug->T_transform classification task. This means that, if you changed your T_transform to something like Color change. The transform classification will be confused as the images will be applied the simclr_aug then.  

By the way, does it matter to change the orders of T_transform and simclr_aug? Thank you!

**Comment by sangwoomo** [comment]
Hi, first sorry for confusion in our transformation code: It is a legacy or our initial research ideas on differentiable augmentation.
The order of rotation, resized random crop (T_transform), and simclr_aug (color augmentations) are order-independent.
We are planning to refactor the code to use torchvision transformations for all augmentations some day :)
