### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by tommying** [alinlab/CSI#37]
Hello，
       You said that "Total batch size should be 512 = 4 (GPU) * 32 (--batch_size option) * 4 (cardinality of shifted transformation set)".    but, I set batch_size=32 and the different number of GPU = 2 or 3. Then, Total batch size always equal to batch_size *2(data augmentation)*4(shifted transformation) no mater what number the GPU set to.

**Comment by jihoontack** [comment]
Hi,

Yes the total batch size is equal to `--batch_size` * `number of GPUs` * `cardinality of shifted transformation`

Hence, if you are using 2 GPUs and trying to reproduce our results, please set `--batch_size 64`

Thank you

**Comment by tommying** [comment]
@jihoontack 
Hi, sir.
My confuse is the total batch size always equal to **batch_size** *2(**data augmentation**)*4(**shifted transformation**) no mater what number the GPU set to.

Use 2 GPUs:
          set --batch_size as 64: the total size of data input to model ([images_pair](https://github.com/alinlab/CSI/blob/60742b60a16501350eca823fcc910ddd10f7a379/training/unsup/simclr_CSI.py#L56)) is 512.
Use 1 GPU:
          set --batch_size as 64: the total size of data input to model (images_pair) is also 512.

Is the total batch size not related to the GPU, but is derived from **batch_size** *2(**data augmentation**)*4(**shifted transformation**) ?

Thank you

**Comment by tommying** [comment]
@jihoontack

**Comment by jihoontack** [comment]
Sorry for the late reply.

It is related to the number of GPUs and you should consider the number of GPUs for calculating the batch size
- `--batch_size * number of GPUs * cardinality of shifted transformation`

Using your example,
- using 2 GPUs and set `--batch_size` as 64: the total batch size will be 512
- using 1 GPU and set `--batch_size` as 64: the total batch size will be 256

Thank you.
