### ISSUE TITLE
The result of using  the checkpoint of unlabeled ImageNet-30

### ISSUE THREAD

**Issue by AtsuMiyai** [alinlab/CSI#38]
Hello!

I use the checkpoint of unlabeled ImageNet-30, I use the following command
`python eval.py --mode ood_pre --dataset imagenet --model resnet18_imagenet --ood_score CSI --shift_trans_type rotation --print_score --ood_samples 10 --resize_factor 0.54 --resize_fix  --load_path imagenet30_unlabeled.model`
The result of this experiment is the following.
[cub best 0.8613] , [stanford_dogs best 0.8144] , [flowers102 best 0.9472] , [places365 best 0.7900] , [food_101 best 0.8802], [caltech_256 best 0.8720], 
[dtd best 0.9696] , [pets best 0.8474]
In datasets except CUB-200 and Dogs, the result is the same as what is reported in the paper.  In CUB-200 and Dogs, the AUROC is different from what is reported in the paper.
In the paper,  the AUROC of CUB-200 is 90.5±0.1, and  the AUROC of Dogs is 97.1±0.1. 
What am I doing wrong?
I'm sorry to trouble you, but could I ask you to answer this question?

**Comment by jihoontack** [comment]
Hi!

We check the result with the checkpoint that we have uploaded and found the same result as in the paper.
[cub CSI 0.9036] [cub best 0.9036] 
[stanford_dogs CSI 0.9694] [stanford_dogs best 0.9694] 
[flowers102 CSI 0.9541] [flowers102 best 0.9541] 
[places365 CSI 0.7900] [places365 best 0.7900] 
[food_101 CSI 0.8802] [food_101 best 0.8802] 
[caltech_256 CSI 0.8720] [caltech_256 best 0.8720] 
[dtd CSI 0.9696] [dtd best 0.9696] 
[pets CSI 0.8474] [pets best 0.8474] 

If you find any reason for this issue, please let us know.

Best,
Jihoon

**Comment by AtsuMiyai** [comment]
Dear Jihoon Tack. 
Thank you for your reply. 
However, no matter how many times I try, the score using dogs datasets is still below 97% (~0.8144). 
Just to confirm, Is the Dogs dataset you are using "the Images (757MB)" from http://vision.stanford.edu/aditya86/ImageNetDogs/?
The images in this Dogs dataset are similar to those in Pets dataset, so it is strange that the Pets score is 0.8474 and the Dogs score is 0.97.

**Comment by smart0eddie** [comment]
Hi, 
I also meet the same issue.

The result of this experiment is the following.
[cub CSI 0.8623] [cub best 0.8623]
[stanford_dogs CSI 0.8139] [stanford_dogs best 0.8139]
[flowers102 CSI 0.9462] [flowers102 best 0.9462]
[places365 CSI 0.7934] [places365 best 0.7934]
[food_101 CSI 0.8843] [food_101 best 0.8843]
[caltech_256 CSI 0.8734] [caltech_256 best 0.8734]
[dtd CSI 0.9695] [dtd best 0.9695]
[pets CSI 0.8461] [pets best 0.8461]
Performance of cub is a little lower than that reported in the paper, while stanford_dogs has a quite large gap.

The following is the command I used  to run with the checkpoint model.
`python eval.py --mode ood_pre --dataset imagenet --model resnet18_imagenet --ood_score CSI --shift_trans_type rotation --ood_samples 10 --resize_factor 0.54 --resize_fix --load_path ../Data/Model/CSI_imagenet30_unlabeled/imagenet30_unlabeled.model --print_score`

I also retrain the model using the following command.
`python train.py --dataset imagenet --model resnet18_imagenet --mode simclr_CSI --shift_trans_type rotation --batch_size 128`

And I get the following results.
[cub CSI 0.8859] [cub best 0.8859]
[stanford_dogs CSI 0.8308] [stanford_dogs best 0.8308]
[flowers102 CSI 0.9528] [flowers102 best 0.9528]
[places365 CSI 0.8129] [places365 best 0.8129]
[food_101 CSI 0.8900] [food_101 best 0.8900]
[caltech_256 CSI 0.8794] [caltech_256 best 0.8794]
[dtd CSI 0.9694] [dtd best 0.9694]
[pets CSI 0.8582] [pets best 0.8582]

Using the following command.
`python eval.py --mode ood_pre --dataset imagenet --model resnet18_imagenet --ood_score CSI --shift_trans_type rotation --ood_samples 10 --resize_factor 0.54 --resize_fix --load_path ../Data/Model/imagenet_resnet18_imagenet_unsup_simclr_CSI_shift_rotation/last.model --print_score`

Where do you get the Dogs dataset?
