### ISSUE TITLE
ood_samples parameter and # of samples in Table 11

### ISSUE THREAD

**Issue by dreamflasher** [alinlab/CSI#4]
I am trying to reproduce Table 11 (appendix D). 
Do I understand correctly that the `ood_samples` parameter of `eval.py` is what you are using to produce the `# of samples` parameter in the table? 
Because surprisingly I find that the ood_samples parameter of eval.py has surprisingly little effect:
CIFAR10 OC

| ood_samples 	| mean    	|
|-------------	|---------	|
| 1           	|  0.9327 	|
| 4           	| 0.93647 	|
| 10          	| 0.93709 	|
| 40          	| 0.93737 	|

Or do I need to adjust the ood_samples parameter in the train.py?

In Table 11 you also report `controlled` results, how do I achieve those? I can't find a parameter in the script to adjust this. Or is this the difference between setting `--resize_fix` and not setting it?

Thank you very much for your help.

**Comment by Jihoon-Tack** [comment]
Thank you for the interest!

I believe your question can be summarized as follows:
(1) Is the `ood_sample` parameter in `eval.py` and `# of samples` in Table 11 the same?
(2) The `ood_sample` parameter doesn't show dramatic performance as Table 11.
(3) How to achieve `controlled` results (of Table 11) in our code.
+ by the way, you don't need to retrain the network to achieve the same results. 

We will answer in following orders: (1) -> (3) -> (2)
(1) Yes, the `ood_sample` parameter in `eval.py` denotes the `# of samples` in Table 11.
(3) Our examples in `READ.md` is `controlled` version. If you want an uncontrolled version, first remove `--resize-fix` and set `--resize_factor` to 0.08.
- `--resize_factor` decides the resizing area range (in Inception crop, we uniformly sample from 0.08~1.0 to obtain the size for cropped image).
- `--resize_fix` fixed the sampling range. For instance, if you set `--resize_factor` to 0.54 and set `--resize_fix`, the size of the cropped image will have 0.54 * original image size.
(2) I think that you have run a `controlled` version with different `# of samples`. Can you rerun the inference with the uncontrolled version as mentioned in the answer (3) above (to obtain the same result with Table 11?)?

If you have more questions please let us know!

Thank you

**Comment by Jihoon-Tack** [comment]
If you have more questions or any problems with running the code, feel free to reopen this issue.

Thank you!
