### ISSUE TITLE
Error while running the training script.

### ISSUE THREAD

**Issue by gouttham** [alinlab/CSI#40]
Hi Folks,
In Transform_layer.py in RandomResizedCropLayer class, in the forward method, 
` 
output = F.adaptive_avg_pool2d(output, self.size)
`

Here the self. size is (32,32,2) and this throws an error.
For adaptive_avg_pool2d we should use the size of 2d right?
I am wondering whether the self.size should be (32,32) or am I missing something?
It would be great if you could shed some clarity on this.

**Comment by jihoontack** [comment]
Hi, Thank you for your interest in our paper!

I believe the self.size should only contain height and width value, e.g., (32, 32)

Best,
Jihoon
