### ISSUE TITLE
GPU requirement for training ImageNet model

### ISSUE THREAD

**Issue by smart0eddie** [alinlab/CSI#41]
Hi
What is your suggested GPU spec. to train ImageNet model?
I am using V100 GPU, but still running out of memory with batch size set to 16 on single GPU

Below is the error message
File "train.py", line 37, in <module>
    train(P, epoch, model, criterion, optimizer, scheduler_warmup, train_loader, logger=logger, **kwargs)
  File "CSI/training/unsup/simclr_CSI.py", line 59, in train
    _, outputs_aux = model(images_pair, simclr=True, penultimate=True, shift=True)

(omitted)

RuntimeError: CUDA out of memory. Tried to allocate 784.00 MiB (GPU 0; 31.75 GiB total capacity; 30.12 GiB already allocated; 405.75 MiB free; 30.14 GiB reserved in total by PyTorch)

**Comment by jihoontack** [comment]
Hi, thank you for your interest in our paper!

We used 4 NVIDIA RTX 2080Ti for the experiments.
I do not remember the exact memory utilization but hope this will help.

Best,
Jihoon
